### ISSUE TITLE
Reading TF values

### ISSUE THREAD

**Issue by bretwitt** [jmscslgroup/bagpy#35]
I'm reading values published to the tf topic and opening up the CSV file. It's split into two columns, Time & transforms but the transforms are stored in what I'm guessing is a YAML format

I'm attempting to parse the yaml and store it like this
```
tf = pd.read_csv(f+"/tf.csv")
for token in tf['transforms']:
    t = token.strip("[]")
    tok_yaml[i] = yaml.load(t, Loader=SafeLoader)
    i+=1
```

but in the CSV that bagpy generates the transforms are stored like this
```
header: 
  seq: 0
  stamp: 
    secs: 1630512225
    nsecs: 303961038
  frame_id: ""gordon/suspension_link""
child_frame_id: ""gordon/back_left_wheel""
transform: 
  translation: 
    x: 0.0979184741812847
    y: 0.0453701778595707
    z: 0.0234999999999999
  rotation: 
    x: 0.0009206402794789245
    y: 0.7071061818577727
    z: -0.0009206402794789279
    w: 0.7071061818577702, header: 
  seq: 0
  stamp: 
    secs: 1630512225
    nsecs: 303961038
  frame_id: ""gordon/suspension_link""
child_frame_id: ""gordon/back_right_wheel""
...
```
where ` w: 0.7071061818577702, header: ` appears to create a malformed mapping that leads to this

```
ScannerError: mapping values are not allowed here
  in "<unicode string>", line 17, column 34:
        w: 0.7071061818577702, header: 
```

I've banged my head against this for way too long, is this an issue with how bagpy is reading the tf format considering how seemingly unconvential everything is stored?
